export default function Head() {
  return (
    <>
      <title>SPECtra</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    </>
  )
}
